CREATE ROLE advisory_ml_user NOINHERIT LOGIN PASSWORD 'CHANGE_ME';
CREATE ROLE control_plane_user NOINHERIT LOGIN PASSWORD 'CHANGE_ME';
CREATE ROLE enforcement_user NOINHERIT LOGIN PASSWORD 'CHANGE_ME';
